[deployment]
deploy_method = "moss"
dns_configured = true
dns_configured_at = "2026-06-08T14:26:37.151956+00:00"
domain = "mosspub.com"
last_deployed_generation_id = "c808cefd68697edb"
last_deployment_at = "2026-07-19T06:56:57+00:00"
last_deployment_url = "https://landing.mosspub.com"
site_id = "landing"

[[deployment.dns_target.records]]
name = "@"
record_type = "A"
ttl = 3600
value = "45.76.13.224"

[[deployment.dns_target.records]]
name = "www"
record_type = "A"
ttl = 3600
value = "45.76.13.224"
